import { Module } from '@nestjs/common'

import { MrpDatabaseModule } from '@/mrp/database/mrp-database.module'
import { ProvisionModule } from '@/shared/provision/provision.module'
import { SharedMessagingModule } from '@/shared/messaging/shared-messaging.module'
import {
  AdjustProductStockController,
  AddRecipeIngredientController,
  CreateAccompanimentTypeController,
  GetProductAccompanimentsController,
  GetProductPricingController,
  GetProductRecipeController,
  GetProductStockController,
  LinkProductAccompanimentController,
  ListAccompanimentTypesController,
  ListProductsController,
  ListStockTransactionsController,
  RegisterProductBrandController,
  RegisterProductController,
  RegisterProductSizeController,
  RegisterProductionController,
  RemoveAccompanimentTypeController,
  RemoveProductAccompanimentController,
  RemoveRecipeIngredientController,
  RemoveProductBrandController,
  RemoveProductSizeController,
  PreviewProductionController,
  SaveRecipeYieldController,
  SaveSingleResaleConfigurationController,
  SaveBrandResaleConfigurationController,
  SetPrimaryProductBrandController,
  RenameAccompanimentTypeController,
  UpdateProductAccompanimentController,
  UpdateProductBrandController,
  UpdateProductSizeController,
  UpdateRecipeIngredientController,
} from '@/mrp/rest/controllers'

@Module({
  imports: [MrpDatabaseModule, ProvisionModule, SharedMessagingModule],
  controllers: [
    CreateAccompanimentTypeController,
    GetProductAccompanimentsController,
    GetProductPricingController,
    LinkProductAccompanimentController,
    ListAccompanimentTypesController,
    RemoveAccompanimentTypeController,
    RemoveProductAccompanimentController,
    RenameAccompanimentTypeController,
    UpdateProductAccompanimentController,
    AdjustProductStockController,
    AddRecipeIngredientController,
    GetProductRecipeController,
    GetProductStockController,
    ListProductsController,
    ListStockTransactionsController,
    RegisterProductBrandController,
    RegisterProductController,
    RegisterProductSizeController,
    RegisterProductionController,
    RemoveRecipeIngredientController,
    RemoveProductBrandController,
    RemoveProductSizeController,
    PreviewProductionController,
    SaveRecipeYieldController,
    SaveSingleResaleConfigurationController,
    SaveBrandResaleConfigurationController,
    SetPrimaryProductBrandController,
    UpdateProductBrandController,
    UpdateProductSizeController,
    UpdateRecipeIngredientController,
  ],
  exports: [MrpDatabaseModule],
})
export class MrpModule {}
