import { Module } from '@nestjs/common'

import { MrpDatabaseModule } from '@/mrp/database/mrp-database.module'
import { MrpProvisionModule } from '@/mrp/provision/mrp-provision.module'
import { ProvisionModule } from '@/shared/provision/provision.module'
import { SharedMessagingModule } from '@/shared/messaging/shared-messaging.module'
import {
  AdjustProductStockController,
  AddRecipeIngredientController,
  ChangeProductCategoriesController,
  ChangeProductUnitController,
  CreateAccompanimentTypeController,
  GetProductAccompanimentsController,
  GetProductCategoryRemovalImpactController,
  GetProductPricingController,
  GetProductRecipeController,
  GetProductRemovalImpactController,
  GetProductSettingsController,
  GetProductStockController,
  LinkProductAccompanimentController,
  ListAccompanimentTypesController,
  ListProductsController,
  ListStockTransactionsController,
  RegisterProductBrandController,
  RegisterProductController,
  RegisterProductSizeController,
  RegisterProductionController,
  RemoveAccompanimentTypeController,
  RemoveProductAccompanimentController,
  RemoveRecipeIngredientController,
  RemoveProductBrandController,
  RemoveProductController,
  RemoveProductSizeController,
  PreviewProductUnitChangeController,
  PreviewProductionController,
  SaveRecipeYieldController,
  SaveSingleResaleConfigurationController,
  SaveBrandResaleConfigurationController,
  SetPrimaryProductBrandController,
  RenameAccompanimentTypeController,
  UpdateProductAccompanimentController,
  UpdateProductBrandController,
  UpdateProductSettingsController,
  UpdateProductSizeController,
  UpdateRecipeIngredientController,
} from '@/mrp/rest/controllers'

@Module({
  imports: [
    MrpDatabaseModule,
    MrpProvisionModule,
    ProvisionModule,
    SharedMessagingModule,
  ],
  controllers: [
    CreateAccompanimentTypeController,
    GetProductAccompanimentsController,
    GetProductPricingController,
    LinkProductAccompanimentController,
    ListAccompanimentTypesController,
    RemoveAccompanimentTypeController,
    RemoveProductAccompanimentController,
    RenameAccompanimentTypeController,
    UpdateProductAccompanimentController,
    AdjustProductStockController,
    AddRecipeIngredientController,
    ChangeProductCategoriesController,
    ChangeProductUnitController,
    GetProductRecipeController,
    GetProductStockController,
    GetProductCategoryRemovalImpactController,
    GetProductRemovalImpactController,
    GetProductSettingsController,
    ListProductsController,
    ListStockTransactionsController,
    RegisterProductBrandController,
    RegisterProductController,
    RegisterProductSizeController,
    RegisterProductionController,
    RemoveRecipeIngredientController,
    RemoveProductBrandController,
    RemoveProductController,
    RemoveProductSizeController,
    PreviewProductionController,
    PreviewProductUnitChangeController,
    SaveRecipeYieldController,
    SaveSingleResaleConfigurationController,
    SaveBrandResaleConfigurationController,
    SetPrimaryProductBrandController,
    UpdateProductBrandController,
    UpdateProductSettingsController,
    UpdateProductSizeController,
    UpdateRecipeIngredientController,
  ],
  exports: [MrpDatabaseModule, MrpProvisionModule],
})
export class MrpModule {}
