@baseUrl = http://localhost:3336
@sessionCookie = replace-with-scoops-session-cookie
@typeId = 00000000-0000-0000-0000-000000000000

### List accompaniment types
GET {{baseUrl}}/accompaniment-types?page=1&pageSize=10
Cookie: {{sessionCookie}}
Accept: application/json

### Create an accompaniment type
POST {{baseUrl}}/accompaniment-types
Cookie: {{sessionCookie}}
Content-Type: application/json

{
  "name": "Calda"
}

### Rename an accompaniment type
PATCH {{baseUrl}}/accompaniment-types/{{typeId}}
Cookie: {{sessionCookie}}
Content-Type: application/json

{
  "name": "Calda de chocolate"
}

### Remove an accompaniment type
DELETE {{baseUrl}}/accompaniment-types/{{typeId}}
Cookie: {{sessionCookie}}
