/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetPasswordIndexRouteImport } from './routes/reset-password/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ForgotPasswordIndexRouteImport } from './routes/forgot-password/index'
import { Route as AccessDeniedIndexRouteImport } from './routes/access-denied/index'
import { Route as OnboardingConfirmRouteImport } from './routes/onboarding/confirm'
import { Route as InvitationAcceptRouteImport } from './routes/invitation/accept'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedSubscriptionIndexRouteImport } from './routes/_authenticated/subscription/index'
import { Route as AuthenticatedShopSettingsIndexRouteImport } from './routes/_authenticated/shop-settings/index'
import { Route as AuthenticatedSalesChannelsIndexRouteImport } from './routes/_authenticated/sales-channels/index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated/orders/index'
import { Route as AuthenticatedDiscountsIndexRouteImport } from './routes/_authenticated/discounts/index'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account/index'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/_authenticated/users/$userId'
import { Route as AuthenticatedSalesNewRouteImport } from './routes/_authenticated/sales/new'
import { Route as AuthenticatedProductsProductIdRouteRouteImport } from './routes/_authenticated/products/$productId/route'
import { Route as AuthenticatedProductsProductIdIndexRouteImport } from './routes/_authenticated/products/$productId/index'
import { Route as AuthenticatedProductsProductIdStockRouteImport } from './routes/_authenticated/products/$productId/stock'
import { Route as AuthenticatedProductsProductIdSettingsRouteImport } from './routes/_authenticated/products/$productId/settings'
import { Route as AuthenticatedProductsProductIdRecipeRouteImport } from './routes/_authenticated/products/$productId/recipe'
import { Route as AuthenticatedProductsProductIdPricesRouteImport } from './routes/_authenticated/products/$productId/prices'
import { Route as AuthenticatedProductsProductIdAccompanimentsRouteImport } from './routes/_authenticated/products/$productId/accompaniments'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordIndexRoute = ResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedIndexRoute = AccessDeniedIndexRouteImport.update({
  id: '/access-denied/',
  path: '/access-denied/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingConfirmRoute = OnboardingConfirmRouteImport.update({
  id: '/onboarding/confirm',
  path: '/onboarding/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationAcceptRoute = InvitationAcceptRouteImport.update({
  id: '/invitation/accept',
  path: '/invitation/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionIndexRoute =
  AuthenticatedSubscriptionIndexRouteImport.update({
    id: '/subscription/',
    path: '/subscription/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedShopSettingsIndexRoute =
  AuthenticatedShopSettingsIndexRouteImport.update({
    id: '/shop-settings/',
    path: '/shop-settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesChannelsIndexRoute =
  AuthenticatedSalesChannelsIndexRouteImport.update({
    id: '/sales-channels/',
    path: '/sales-channels/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiscountsIndexRoute =
  AuthenticatedDiscountsIndexRouteImport.update({
    id: '/discounts/',
    path: '/discounts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesNewRoute = AuthenticatedSalesNewRouteImport.update({
  id: '/sales/new',
  path: '/sales/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsProductIdRouteRoute =
  AuthenticatedProductsProductIdRouteRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsProductIdIndexRoute =
  AuthenticatedProductsProductIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProductsProductIdRouteRoute,
  } as any)
const AuthenticatedProductsProductIdStockRoute =
  AuthenticatedProductsProductIdStockRouteImport.update({
    id: '/stock',
    path: '/stock',
    getParentRoute: () => AuthenticatedProductsProductIdRouteRoute,
  } as any)
const AuthenticatedProductsProductIdSettingsRoute =
  AuthenticatedProductsProductIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedProductsProductIdRouteRoute,
  } as any)
const AuthenticatedProductsProductIdRecipeRoute =
  AuthenticatedProductsProductIdRecipeRouteImport.update({
    id: '/recipe',
    path: '/recipe',
    getParentRoute: () => AuthenticatedProductsProductIdRouteRoute,
  } as any)
const AuthenticatedProductsProductIdPricesRoute =
  AuthenticatedProductsProductIdPricesRouteImport.update({
    id: '/prices',
    path: '/prices',
    getParentRoute: () => AuthenticatedProductsProductIdRouteRoute,
  } as any)
const AuthenticatedProductsProductIdAccompanimentsRoute =
  AuthenticatedProductsProductIdAccompanimentsRouteImport.update({
    id: '/accompaniments',
    path: '/accompaniments',
    getParentRoute: () => AuthenticatedProductsProductIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invitation/accept': typeof InvitationAcceptRoute
  '/onboarding/confirm': typeof OnboardingConfirmRoute
  '/access-denied/': typeof AccessDeniedIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/login/': typeof LoginIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRouteRouteWithChildren
  '/sales/new': typeof AuthenticatedSalesNewRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/discounts/': typeof AuthenticatedDiscountsIndexRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/sales-channels/': typeof AuthenticatedSalesChannelsIndexRoute
  '/shop-settings/': typeof AuthenticatedShopSettingsIndexRoute
  '/subscription/': typeof AuthenticatedSubscriptionIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/products/$productId/accompaniments': typeof AuthenticatedProductsProductIdAccompanimentsRoute
  '/products/$productId/prices': typeof AuthenticatedProductsProductIdPricesRoute
  '/products/$productId/recipe': typeof AuthenticatedProductsProductIdRecipeRoute
  '/products/$productId/settings': typeof AuthenticatedProductsProductIdSettingsRoute
  '/products/$productId/stock': typeof AuthenticatedProductsProductIdStockRoute
  '/products/$productId/': typeof AuthenticatedProductsProductIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invitation/accept': typeof InvitationAcceptRoute
  '/onboarding/confirm': typeof OnboardingConfirmRoute
  '/access-denied': typeof AccessDeniedIndexRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/login': typeof LoginIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/sales/new': typeof AuthenticatedSalesNewRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/discounts': typeof AuthenticatedDiscountsIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/sales-channels': typeof AuthenticatedSalesChannelsIndexRoute
  '/shop-settings': typeof AuthenticatedShopSettingsIndexRoute
  '/subscription': typeof AuthenticatedSubscriptionIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/products/$productId/accompaniments': typeof AuthenticatedProductsProductIdAccompanimentsRoute
  '/products/$productId/prices': typeof AuthenticatedProductsProductIdPricesRoute
  '/products/$productId/recipe': typeof AuthenticatedProductsProductIdRecipeRoute
  '/products/$productId/settings': typeof AuthenticatedProductsProductIdSettingsRoute
  '/products/$productId/stock': typeof AuthenticatedProductsProductIdStockRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/invitation/accept': typeof InvitationAcceptRoute
  '/onboarding/confirm': typeof OnboardingConfirmRoute
  '/access-denied/': typeof AccessDeniedIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/login/': typeof LoginIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/_authenticated/products/$productId': typeof AuthenticatedProductsProductIdRouteRouteWithChildren
  '/_authenticated/sales/new': typeof AuthenticatedSalesNewRoute
  '/_authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/discounts/': typeof AuthenticatedDiscountsIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/sales-channels/': typeof AuthenticatedSalesChannelsIndexRoute
  '/_authenticated/shop-settings/': typeof AuthenticatedShopSettingsIndexRoute
  '/_authenticated/subscription/': typeof AuthenticatedSubscriptionIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/products/$productId/accompaniments': typeof AuthenticatedProductsProductIdAccompanimentsRoute
  '/_authenticated/products/$productId/prices': typeof AuthenticatedProductsProductIdPricesRoute
  '/_authenticated/products/$productId/recipe': typeof AuthenticatedProductsProductIdRecipeRoute
  '/_authenticated/products/$productId/settings': typeof AuthenticatedProductsProductIdSettingsRoute
  '/_authenticated/products/$productId/stock': typeof AuthenticatedProductsProductIdStockRoute
  '/_authenticated/products/$productId/': typeof AuthenticatedProductsProductIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invitation/accept'
    | '/onboarding/confirm'
    | '/access-denied/'
    | '/forgot-password/'
    | '/login/'
    | '/onboarding/'
    | '/reset-password/'
    | '/products/$productId'
    | '/sales/new'
    | '/users/$userId'
    | '/account/'
    | '/discounts/'
    | '/orders/'
    | '/products/'
    | '/sales-channels/'
    | '/shop-settings/'
    | '/subscription/'
    | '/users/'
    | '/products/$productId/accompaniments'
    | '/products/$productId/prices'
    | '/products/$productId/recipe'
    | '/products/$productId/settings'
    | '/products/$productId/stock'
    | '/products/$productId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invitation/accept'
    | '/onboarding/confirm'
    | '/access-denied'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/sales/new'
    | '/users/$userId'
    | '/account'
    | '/discounts'
    | '/orders'
    | '/products'
    | '/sales-channels'
    | '/shop-settings'
    | '/subscription'
    | '/users'
    | '/products/$productId/accompaniments'
    | '/products/$productId/prices'
    | '/products/$productId/recipe'
    | '/products/$productId/settings'
    | '/products/$productId/stock'
    | '/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/invitation/accept'
    | '/onboarding/confirm'
    | '/access-denied/'
    | '/forgot-password/'
    | '/login/'
    | '/onboarding/'
    | '/reset-password/'
    | '/_authenticated/products/$productId'
    | '/_authenticated/sales/new'
    | '/_authenticated/users/$userId'
    | '/_authenticated/account/'
    | '/_authenticated/discounts/'
    | '/_authenticated/orders/'
    | '/_authenticated/products/'
    | '/_authenticated/sales-channels/'
    | '/_authenticated/shop-settings/'
    | '/_authenticated/subscription/'
    | '/_authenticated/users/'
    | '/_authenticated/products/$productId/accompaniments'
    | '/_authenticated/products/$productId/prices'
    | '/_authenticated/products/$productId/recipe'
    | '/_authenticated/products/$productId/settings'
    | '/_authenticated/products/$productId/stock'
    | '/_authenticated/products/$productId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  InvitationAcceptRoute: typeof InvitationAcceptRoute
  OnboardingConfirmRoute: typeof OnboardingConfirmRoute
  AccessDeniedIndexRoute: typeof AccessDeniedIndexRoute
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof ResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password/': {
      id: '/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied/': {
      id: '/access-denied/'
      path: '/access-denied'
      fullPath: '/access-denied/'
      preLoaderRoute: typeof AccessDeniedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/confirm': {
      id: '/onboarding/confirm'
      path: '/onboarding/confirm'
      fullPath: '/onboarding/confirm'
      preLoaderRoute: typeof OnboardingConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation/accept': {
      id: '/invitation/accept'
      path: '/invitation/accept'
      fullPath: '/invitation/accept'
      preLoaderRoute: typeof InvitationAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription/': {
      id: '/_authenticated/subscription/'
      path: '/subscription'
      fullPath: '/subscription/'
      preLoaderRoute: typeof AuthenticatedSubscriptionIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shop-settings/': {
      id: '/_authenticated/shop-settings/'
      path: '/shop-settings'
      fullPath: '/shop-settings/'
      preLoaderRoute: typeof AuthenticatedShopSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales-channels/': {
      id: '/_authenticated/sales-channels/'
      path: '/sales-channels'
      fullPath: '/sales-channels/'
      preLoaderRoute: typeof AuthenticatedSalesChannelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discounts/': {
      id: '/_authenticated/discounts/'
      path: '/discounts'
      fullPath: '/discounts/'
      preLoaderRoute: typeof AuthenticatedDiscountsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/new': {
      id: '/_authenticated/sales/new'
      path: '/sales/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof AuthenticatedSalesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/$productId': {
      id: '/_authenticated/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthenticatedProductsProductIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/$productId/': {
      id: '/_authenticated/products/$productId/'
      path: '/'
      fullPath: '/products/$productId/'
      preLoaderRoute: typeof AuthenticatedProductsProductIdIndexRouteImport
      parentRoute: typeof AuthenticatedProductsProductIdRouteRoute
    }
    '/_authenticated/products/$productId/stock': {
      id: '/_authenticated/products/$productId/stock'
      path: '/stock'
      fullPath: '/products/$productId/stock'
      preLoaderRoute: typeof AuthenticatedProductsProductIdStockRouteImport
      parentRoute: typeof AuthenticatedProductsProductIdRouteRoute
    }
    '/_authenticated/products/$productId/settings': {
      id: '/_authenticated/products/$productId/settings'
      path: '/settings'
      fullPath: '/products/$productId/settings'
      preLoaderRoute: typeof AuthenticatedProductsProductIdSettingsRouteImport
      parentRoute: typeof AuthenticatedProductsProductIdRouteRoute
    }
    '/_authenticated/products/$productId/recipe': {
      id: '/_authenticated/products/$productId/recipe'
      path: '/recipe'
      fullPath: '/products/$productId/recipe'
      preLoaderRoute: typeof AuthenticatedProductsProductIdRecipeRouteImport
      parentRoute: typeof AuthenticatedProductsProductIdRouteRoute
    }
    '/_authenticated/products/$productId/prices': {
      id: '/_authenticated/products/$productId/prices'
      path: '/prices'
      fullPath: '/products/$productId/prices'
      preLoaderRoute: typeof AuthenticatedProductsProductIdPricesRouteImport
      parentRoute: typeof AuthenticatedProductsProductIdRouteRoute
    }
    '/_authenticated/products/$productId/accompaniments': {
      id: '/_authenticated/products/$productId/accompaniments'
      path: '/accompaniments'
      fullPath: '/products/$productId/accompaniments'
      preLoaderRoute: typeof AuthenticatedProductsProductIdAccompanimentsRouteImport
      parentRoute: typeof AuthenticatedProductsProductIdRouteRoute
    }
  }
}

interface AuthenticatedProductsProductIdRouteRouteChildren {
  AuthenticatedProductsProductIdAccompanimentsRoute: typeof AuthenticatedProductsProductIdAccompanimentsRoute
  AuthenticatedProductsProductIdPricesRoute: typeof AuthenticatedProductsProductIdPricesRoute
  AuthenticatedProductsProductIdRecipeRoute: typeof AuthenticatedProductsProductIdRecipeRoute
  AuthenticatedProductsProductIdSettingsRoute: typeof AuthenticatedProductsProductIdSettingsRoute
  AuthenticatedProductsProductIdStockRoute: typeof AuthenticatedProductsProductIdStockRoute
  AuthenticatedProductsProductIdIndexRoute: typeof AuthenticatedProductsProductIdIndexRoute
}

const AuthenticatedProductsProductIdRouteRouteChildren: AuthenticatedProductsProductIdRouteRouteChildren =
  {
    AuthenticatedProductsProductIdAccompanimentsRoute:
      AuthenticatedProductsProductIdAccompanimentsRoute,
    AuthenticatedProductsProductIdPricesRoute:
      AuthenticatedProductsProductIdPricesRoute,
    AuthenticatedProductsProductIdRecipeRoute:
      AuthenticatedProductsProductIdRecipeRoute,
    AuthenticatedProductsProductIdSettingsRoute:
      AuthenticatedProductsProductIdSettingsRoute,
    AuthenticatedProductsProductIdStockRoute:
      AuthenticatedProductsProductIdStockRoute,
    AuthenticatedProductsProductIdIndexRoute:
      AuthenticatedProductsProductIdIndexRoute,
  }

const AuthenticatedProductsProductIdRouteRouteWithChildren =
  AuthenticatedProductsProductIdRouteRoute._addFileChildren(
    AuthenticatedProductsProductIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProductsProductIdRouteRoute: typeof AuthenticatedProductsProductIdRouteRouteWithChildren
  AuthenticatedSalesNewRoute: typeof AuthenticatedSalesNewRoute
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
  AuthenticatedDiscountsIndexRoute: typeof AuthenticatedDiscountsIndexRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedSalesChannelsIndexRoute: typeof AuthenticatedSalesChannelsIndexRoute
  AuthenticatedShopSettingsIndexRoute: typeof AuthenticatedShopSettingsIndexRoute
  AuthenticatedSubscriptionIndexRoute: typeof AuthenticatedSubscriptionIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProductsProductIdRouteRoute:
    AuthenticatedProductsProductIdRouteRouteWithChildren,
  AuthenticatedSalesNewRoute: AuthenticatedSalesNewRoute,
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  AuthenticatedDiscountsIndexRoute: AuthenticatedDiscountsIndexRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedSalesChannelsIndexRoute: AuthenticatedSalesChannelsIndexRoute,
  AuthenticatedShopSettingsIndexRoute: AuthenticatedShopSettingsIndexRoute,
  AuthenticatedSubscriptionIndexRoute: AuthenticatedSubscriptionIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  InvitationAcceptRoute: InvitationAcceptRoute,
  OnboardingConfirmRoute: OnboardingConfirmRoute,
  AccessDeniedIndexRoute: AccessDeniedIndexRoute,
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
