import {
  ArrowRight,
  Check,
  CircleCheck,
  DoorOpen,
  Eye,
  EyeOff,
  IceCreamBowl,
  KeyRound,
  Link2Off,
  LockKeyhole,
  Mail,
  MailCheck,
  MailWarning,
  Route,
  Send,
  ShieldCheck,
  Sparkles,
  Store,
  TriangleAlert,
  UserCheck,
  UserPlus,
  Users,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

import type { IconName } from '../types'

export const ICONS: Record<IconName, LucideIcon> = {
  arrow: ArrowRight,
  check: Check,
  'circle-check': CircleCheck,
  'door-open': DoorOpen,
  eye: Eye,
  'eye-off': EyeOff,
  'ice-cream-bowl': IceCreamBowl,
  key: KeyRound,
  'link-off': Link2Off,
  lock: LockKeyhole,
  mail: Mail,
  'mail-check': MailCheck,
  'mail-warning': MailWarning,
  route: Route,
  send: Send,
  'shield-check': ShieldCheck,
  sparkles: Sparkles,
  store: Store,
  'triangle-alert': TriangleAlert,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  users: Users,
}
