import {
  ArrowDown,
  ArrowDownUp,
  ArrowRight,
  ArrowUp,
  Bell,
  CalendarDays,
  ChevronDown,
  Check,
  CircleCheck,
  Clock3,
  ClipboardList,
  CreditCard,
  DoorOpen,
  Ellipsis,
  Eye,
  EyeOff,
  Filter,
  ChevronLeft,
  ChevronRight,
  IceCreamBowl,
  Info,
  KeyRound,
  LayoutDashboard,
  Link2Off,
  LockKeyhole,
  Mail,
  MailCheck,
  MailWarning,
  Monitor,
  Package,
  Plus,
  Pencil,
  Route,
  Search,
  Send,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  Sparkles,
  Store,
  Tags,
  Trash2,
  TriangleAlert,
  UserCheck,
  UserPlus,
  UserRound,
  Users,
  X,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

import type { IconName } from '../types'

export const ICONS: Record<IconName, LucideIcon> = {
  arrow: ArrowRight,
  'arrow-down': ArrowDown,
  'arrow-down-up': ArrowDownUp,
  'arrow-up': ArrowUp,
  bell: Bell,
  calendar: CalendarDays,
  check: Check,
  'circle-check': CircleCheck,
  clock: Clock3,
  'clipboard-list': ClipboardList,
  'credit-card': CreditCard,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'door-open': DoorOpen,
  ellipsis: Ellipsis,
  filter: Filter,
  email: Mail,
  eye: Eye,
  'eye-off': EyeOff,
  'ice-cream-bowl': IceCreamBowl,
  info: Info,
  key: KeyRound,
  lock: LockKeyhole,
  'link-off': Link2Off,
  mail: Mail,
  'mail-check': MailCheck,
  'mail-warning': MailWarning,
  monitor: Monitor,
  name: UserRound,
  'new-password': KeyRound,
  package: Package,
  plus: Plus,
  pencil: Pencil,
  password: KeyRound,
  route: Route,
  search: Search,
  send: Send,
  shield: Shield,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  'shopping-cart': ShoppingCart,
  sparkles: Sparkles,
  store: Store,
  tags: Tags,
  'trash-2': Trash2,
  'triangle-alert': TriangleAlert,
  'user-check': UserCheck,
  'user-plus': UserPlus,
  'user-round': UserRound,
  users: Users,
  x: X,
  'confirm-password': KeyRound,
  'layout-dashboard': LayoutDashboard,
}
