@baseUrl = http://localhost:3336
@sessionCookie = replace-with-scoops-session-cookie

### Get current establishment settings
GET {{baseUrl}}/establishments/current
Cookie: {{sessionCookie}}
Accept: application/json

### Change current establishment name
PATCH {{baseUrl}}/establishments/current/name
Cookie: {{sessionCookie}}
Content-Type: application/json

{
  "name": "Scoops Centro"
}
