@baseUrl = http://localhost:3336
@globalSearchQuery = vanilla

### Authenticated global search for the current account
GET {{baseUrl}}/global-search?q={{globalSearchQuery}}
Accept: application/json
Cookie: {{sessionCookie}}
