import type { ProductTelemetryWorkflow } from '#shared/interfaces/product-telemetry-workflow.ts'

export type ProductTelemetryFieldName<TWorkflow extends ProductTelemetryWorkflow> =
  TWorkflow extends 'onboarding'
    ? 'establishmentName' | 'managerName' | 'email' | 'password' | 'passwordConfirmation'
    : TWorkflow extends 'product_creation'
      ?
          | 'name'
          | 'unit'
          | 'categories'
          | 'stockControl'
          | 'allowNegativeStock'
          | 'currentUnitCost'
          | 'initialStock'
          | 'idealStock'
          | 'brands'
          | 'brands.*.id'
          | 'brands.*.name'
          | 'brands.*.unit'
          | 'brands.*.packageQuantity'
          | 'brands.*.packagePrice'
          | 'brands.*.packageCount'
          | 'brands.*.isPrimary'
      : TWorkflow extends 'stock_entry' | 'stock_write_off'
        ? 'inputMode' | 'quantity' | 'justification' | 'packageQuantity'
        : 'batches' | 'quantity'
